In [3]:
import pandas as pd

In [4]:
link = 'https://storage.yandexcloud.net/lms-itmo-ru-files-27a87tyf/Data_storage_and_processing/Ind_2/task2_363981.csv'
df = pd.read_csv(link)
df

           <DATE>    <TIME>  <OPEN>  <HIGH>   <LOW>  <CLOSE>  <VOL>
0      01.09.2020  10:00:00  107933  114984  107933   109653     76
1      01.09.2020  10:01:00  113893  115033  108260   110409     22
2      01.09.2020  10:02:00  110410  115232  107957   115218     94
3      01.09.2020  10:03:00  113598  115291  108048   109899     73
4      01.09.2020  10:04:00  110591  115233  108021   110062     81
...           ...       ...     ...     ...     ...      ...    ...
51721  30.12.2020  19:56:00  110783  115280  107964   108332     95
51722  30.12.2020  19:57:00  110982  115230  107947   113481     92
51723  30.12.2020  19:58:00  108319  115217  107935   108960     84
51724  30.12.2020  19:59:00  108107  115249  108013   110556     44
51725  30.12.2020  20:00:00  111840  114871  108007   110110     80

[51726 rows x 7 columns]

In [9]:
df['<PRICE>'] = (df['<OPEN>'] + df['<CLOSE>'] + df['<LOW>'] + df['<HIGH>'])/4

In [ ]:
filtered_row = df[(df['<DATE>'] == '03.11.2020') & (df['<TIME>'] == '11:30:00')]
filtered_row

,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,mean open,mean_price
26853,03.11.2020,11:30:00,111015,115244,108266,114245,50,111586.222422,112192.5

In [22]:
df['<TOTAL>'] = df['<PRICE>']*df['<VOL>']

filtered_rows = df[df['<DATE>'] == '30.11.2020']

# Вычисляем суммарный оборот (предположим, что оборот хранится в столбце '<VOL>')
total_turnover = filtered_rows['<TOTAL>'].sum()
t1 = filtered_rows.sum()
print(total_turnover, t1)

3389267124.0 <DATE>     30.11.202030.11.202030.11.202030.11.202030.11....
<TIME>     10:00:0010:01:0010:02:0010:03:0010:04:0010:05:...
<OPEN>                                              66380315
<HIGH>                                              68643158
<LOW>                                               64384875
<CLOSE>                                             66543118
<VOL>                                                  30372
<PRICE>                                           66487866.5
<TOTAL>                                         3389267124.0
dtype: object

In [32]:
rows = df[df['<DATE>'] == '07.10.2020']
cnt = rows['<OPEN>'] > rows['<CLOSE>']
cnt.sum()

276

In [40]:
df['weekend']= pd.to_datetime(df['<DATE>'], dayfirst = True).dt.day_name()
rows = df.loc[(df['weekend'] == 'Tuesday') & (pd.to_datetime(df['<DATE>'], dayfirst = True).dt.month == 10)]
round(rows['<TOTAL>'].mean())

5526268